# Generated by Django 5.1.5 on 2025-01-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('image', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('maxprice', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('minprice', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
